image: openjdk:15-alpine

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew classes

  tags:
    release-*:
      - step:
          name: Prepare signing key
          script:
            - apk add openssl
            - echo "$SIGNING_KEY" > private-key.gpg.enc
            - openssl aes-256-cbc -a -k $SIGNING_PWD -in private-key.gpg.enc -out signing-key -d
            - gpg --import signing-key
            - shred signing-key
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew clean build
            - bash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD

  pull-requests:
    feature/*:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew check jacocoTestReport
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - step:
          name: Quality Gate
          caches:
            - gradle
          script:
            - bash ./gradlew sonarqube

  branches:
    master:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew check jacocoTestReport
          artifacts:
            - ./.gradle/**
            - ./**/build/**
          after-script:
            - bash <(curl -s https://codecov.io/bash) -s "*/build/reports/*" -f '*report.xml'
      - parallel:
          - step:
              name: Deploy snapshot
              caches:
                - gradle
              script:
                - apk add openssl
                - echo "$SIGNING_KEY" > private-key.gpg.enc
                - openssl aes-256-cbc -a -k $SIGNING_PWD -in private-key.gpg.enc -out signing-key -d
                - gpg --import signing-key
                - shred signing-key
                - bash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD
          - step:
              name: Quality gate
              caches:
                - gradle
              script:
                - bash ./gradlew sonarqube
