image: maven:3.6-openjdk-15

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew classes

  tags:
    release-*:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - ash ./gradlew clean build
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - step:
          name: Publish release
          caches:
            - gradle
          script:
            - export GPG_TTY=$(tty)
            - openssl aes-256-cbc -a -k $SIGNING_PWD -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --import private-key.gpg
            - bash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD

  pull-requests:
    feature/*:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew check #jacocoTestReport -- jacoco does not work with java 15 and gradle yet
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - step:
          name: Quality Gate
          caches:
            - gradle
          script:
            - bash ./gradlew sonarqube

  branches:
    master:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew check #jacocoTestReport -- jacoco does not work with java 15 and gradle yet
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - parallel:
          - step:
              name: Deploy snapshot
              caches:
                - gradle
              script:
                - export GPG_TTY=$(tty)
                - openssl aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out private-key.gpg -d
                - gpg --import private-key.gpg
                - bash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD
          - step:
              name: Quality gate
              caches:
                - gradle
              script:
                - bash ./gradlew sonarqube
