image: openjdk:14

pipelines:
  default:
    - step:
        name: Build software
        caches:
          - gradle
        script:
          - bash ./gradlew clean test
        after-script:
          - bash ./gradlew jacocoTestReport
          - bash <(curl -s https://codecov.io/bash)