image: openjdk:15-alpine

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - ash ./gradlew classes

  tags:
    release-*:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - ash ./gradlew clean build
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - step:
          name: Publish release
          caches:
            - gradle
          script:
            - apk add openssl
            - echo "$SIGNING_KEY" > private-key.gpg.enc
            - openssl aes-256-cbc -a -k $SIGNING_PWD -in private-key.gpg.enc -out signing-key -d
            - gpg --import signing-key
            - shred signing-key
            - ash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD

  pull-requests:
    feature/*:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - ash ./gradlew check #jacocoTestReport -- jacoco does not work with java 15 and gradle yet
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - step:
          name: Quality Gate
          caches:
            - gradle
          script:
            - ash ./gradlew sonarqube

  branches:
    master:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - ash ./gradlew check #jacocoTestReport -- jacoco does not work with java 15 and gradle yet
          artifacts:
            - ./.gradle/**
            - ./**/build/**
      - parallel:
          - step:
              name: Deploy snapshot
              caches:
                - gradle
              script:
                - apk add openssl
                - echo "$SIGNING_KEY" > private-key.gpg.enc
                - openssl aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out signing-key -d
                - gpg --import signing-key
                - shred signing-key
                - ash ./gradlew publish -Psigning.keyId=$GPG_KEY -Psigning.password=$GPG_PASSWORD
          - step:
              name: Quality gate
              caches:
                - gradle
              script:
                - ash ./gradlew sonarqube
