image: openjdk:14

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew test
          - if [ $? -eq 0 ]; then bash <(curl -s https://codecov.io/bash); fi