image: openjdk:14

pipelines:
  default:
    - step:
        name: Test commit quality
        caches:
          - gradle
        script:
          - bash ./gradlew check
        after-script:
          - bash ./gradlew jacocoTestReport
          - bash <(curl -s https://codecov.io/bash) -s "*/build/report/*"
