image: maven:3.6.3-amazoncorretto-15

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew classes

  pull-requests:
    feature/*:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew -x javadoc check jacocoTestReport
          artifacts:
            - .gradle/**
            - "**/build/**"
      - step:
          name: Quality Gate
          caches:
            - gradle
          script:
            - bash ./gradlew -x javadoc sonarqube

  branches:
    master:
      - step:
          name: Build software
          caches:
            - gradle
          script:
            - bash ./gradlew -x javadoc check jacocoTestReport
          artifacts:
            - .gradle/**
            - "**/build/**"
      - parallel:
          - step:
              name: Deploy snapshot
              caches:
                - gradle
              script:
                - export GPG_TTY=$(tty)
                - yum install openssl11 gnupg -y
                - openssl11 aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out private-key.gpg -d
                - gpg --import private-key.gpg
                - printf "signing.keyId=$GPG_KEY\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=$BITBUCKET_CLONE_DIR/private-key.gpg" > ~/.gradle/gradle.properties
                - bash ./gradlew -x javadoc publish
          - step:
              name: Quality gate
              caches:
                - gradle
              script:
                - bash ./gradlew -x javadoc sonarqube

    release/*:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew clean build
          artifacts:
            - .gradle/**
            - "**/build/libs/*.jar"
      - step:
          name: Publish release
          trigger: manual
          caches:
            - gradle
          script:
            - export GPG_TTY=$(tty)
            - yum install openssl11 gnupg -y
            - openssl11 aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --import private-key.gpg
            - printf "signing.keyId=$GPG_KEY\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=$BITBUCKET_CLONE_DIR/private-key.gpg" > ~/.gradle/gradle.properties
            - bash ./gradlew -x jar publish
