image: openjdk:14

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew classes

  pull-requests:
    feature/*:
      - step:
          caches:
            - gradle
          script:
            - bash ./gradlew check jacocoTestReport
            - bash ./gradlew sonarqube
      - step:
          name: Check Quality Gate on SonarCloud
          script:
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.3

  branches:
    master:
      - step:
          caches:
            - gradle
          script:
            - bash ./gradlew check jacocoTestReport
            - bash ./gradlew sonarqube
          after-script:
            - bash <(curl -s https://codecov.io/bash) -s "*/build/reports/*" -f '*report.xml'
