name: Build Snapshot

on:
  push:
    branches:
      - master

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/component-build.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Configure Java version
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Publish artifacts
        run: |
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew publish -x check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
